name: repository
description: Ember 8 data and repository package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  deposit: ^0.0.1
  deposit_firestore: ^0.0.1
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  very_good_analysis: ^2.4.0
